title: Tharun Challani's QA Portfolio
description: A portfolio showcasing 9+ years of QA experience.
theme: jekyll-theme-cayman
baseurl: "/TharunChallani-QA-Portfolio"
url: "https://tharunchallani95.github.io"