name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Update to the latest version

    - name: Set up Node.js
      uses: actions/setup-node@v4  # Update to the latest version
      with:
        node-version: '18'  # You can keep this as your required Node.js version

    - name: Install dependencies
      run: npm install
      working-directory: Automation-Project/Playwright

    - name: Run Playwright tests
      run: npx playwright test
      working-directory: Automation-Project/Playwright
